"""Added timestamp for reviews

Revision ID: 0a38820a85e5
Revises: 49de41d88643
Create Date: 2023-09-24 21:54:00.772258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a38820a85e5'
down_revision: Union[str, None] = '49de41d88643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reviews', 'created')
    # ### end Alembic commands ###
