"""Added Genres table

Revision ID: 3261247ec3f2
Revises: 0a38820a85e5
Create Date: 2023-09-26 09:19:58.345064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3261247ec3f2'
down_revision: Union[str, None] = '0a38820a85e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Books Genres',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Reviews', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('Books Genres')
    op.drop_table('Genres')
    # ### end Alembic commands ###
